# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        self.pushButton = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton.setGeometry(QtCore.QRect(500, 370, 600, 100))
        self.pushButton.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    font: 63 22pt \"Cascadia Code SemiBold\";\n"
            "color: White;\n"
            "border: 2px solid #555;\n"
            "border-radius: 20px;\n"
            "border-style: outset;\n"
            "padding: 1px;\n"
            "    background-color: rgb(180, 213, 255);\n"
            "    \n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "background-color: ;\n"
            "    color: green;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "border-style: inset;\n"
            "background: white\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 490, 600, 100))
        self.pushButton_2.setStyleSheet(
            "\n"
            "QPushButton {\n"
            "    font: 63 22pt \"Cascadia Code SemiBold\";\n"
            "color: White;\n"
            "border: 2px solid #555;\n"
            "border-radius: 20px;\n"
            "border-style: outset;\n"
            "padding: 1px;\n"
            "    background-color: rgb(180, 213, 255);\n"
            "    \n"
            "}\n"
            "\n"
            "QPushButton:hover {\n"
            "background-color: ;\n"
            "    color: green;\n"
            "}\n"
            "\n"
            "QPushButton:pressed {\n"
            "border-style: inset;\n"
            "background: white\n"
            "}"
        )
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(670, -40, 800, 400))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label.setFont(font)
        self.label.setStyleSheet(
            "font: 63 22pt \"Cascadia Code SemiBold\";\n" "color: White;\n" ""
        )
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(400, 300, 901, 50))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code SemiBold")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "font: 63 22pt \"Cascadia Code SemiBold\";\n" "color: black;\n" ""
        )
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButton_2.setText(_translate("Dialog", "PushButton"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
